INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('1', 'Player', '1', 'sdfsdf@woo.com', '555 Woodward', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('2', 'Moe', 'Merc', 'merc@gmail.om', '1570 Woodward', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('3', 'Verona  ', 'Myles  ', 'x906jggmwa@7j7vsg3.com', '970 Harvest Isle', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('4', 'Rudy  ', 'Brett  ', 'a0hsknypcv_j@g6f-dlfp7.com', '6967 Hidden Treasure Street', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('5', 'Trevor  ', 'Isiah  ', 'fb9zi@yo1ym8ev.com', '8398 Grand Forest Link', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('6', 'Jacqueline  ', 'Stan  ', '_mm-vs@41r8bwl93wc.com', '8334 Clear Elk Centre', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('7', 'Jadwiga  ', 'Aura  ', '2bfe35rz0a9z.@h093q2r8x.com', '3986 Colonial Field', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('8', 'Cammie  ', 'Leia  ', '-rluteaif@em783t54p.com', '9440 Lazy Branch Mountain', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('9', 'Pam  ', 'Benedict  ', 'yr3p9r96d@oma5xtm2tu8.com', '6578 Pleasant View Cove', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('10', 'Micheal  ', 'Kacey  ', '5w1mps49kom@a3hqy-tblt70.com', '8488 Silver Townline', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('11', 'Slyvia  ', 'Dollie  ', '2x5@wjzo6n1.com', '5801 Gentle Autoroute', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('12', 'Josephine  ', 'Augustus  ', 'sed7qd@wxtjwcl9wh7.com', '4152 Silent Prairie Point', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('13', 'Magnolia  ', 'Lisette  ', 'xkihu0woklx@d31gwfji.com', '937 Little Boulevard', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('14', 'Alysa  ', 'Cathrine  ', 'tp86mraieq6o@ya7uvi4767x.com', '7221 Cotton Goose Vista', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('15', 'Sumiko  ', 'Trisha  ', 'j2msse_8_4@gp3psh.com', '868 Wishing Island Downs', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('16', 'Lucia  ', 'Claudie  ', '8i4p6@ahy5dlogudsa.com', '4262 Middle Fawn Diversion', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('17', 'Alanna  ', 'Camellia  ', 'aqw4x.uas3@invqd-idh8.com', '9205 Sleepy Leaf Thicket', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('18', 'Timika  ', 'Josh  ', 'ils5p.6_w5ofv_@ec0w4g0o.com', '3410 Round Highway', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('19', 'Delores  ', 'Tawny  ', 'o8fw5c9aoo5@3mw19o.com', '2937 Fallen Limits', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('20', 'Cheri  ', 'Ione  ', '-bi.@a53g4f.com', '7798 Blue Ramp', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('21', 'Nicholas  ', 'Rachel  ', 'u1aerdarrpji3@59yia2fc0fc4.com', '672 High Chase', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('22', 'Marion  ', 'Esteban  ', 'xccsx3s3gw3ybe@7j61ht9.com', '9363 Emerald River Via', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('23', 'Raina  ', 'Ethelyn  ', 'dkjin@bevyhxe.com', '8503 Foggy Bluff Dale', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('24', 'Kareen  ', 'Alice  ', 'xuvgkghobrj4y@2z6b3fkz.com', '5931 Quaking Bear Alley', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('25', 'Margarito  ', 'Mia  ', 'ed.m3ded1@yy685bk7.com', '2245 Lost Sky Island', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('26', 'Rosalinda  ', 'Ursula  ', 'yekm.mcex@bw9fz8rpa.com', '2849 Cinder Cider End', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('27', 'Delta  ', 'Elwanda  ', '1jguf.wr8c@0sgj4fu7k.com', '5394 Golden Wagon Campus', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('28', 'Melody  ', 'Tennie  ', '9ddw.@u--esynyhsy4.com', '7871 Jagged Parade', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('29', 'Tierra  ', 'Reena  ', '70aag7g32r9yn_2@89i89npw1.com', '136 Dewy Butterfly Loop', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('30', 'Elisa  ', 'Retha  ', 'i4xg@kqdlqjfw06b.com', '9182 Tawny Grove Run', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('31', 'Emerson  ', 'Katherin  ', 'p6gl3piz5ykt3@c1sy84e-e.com', '7976 Easy Anchor Pike', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('32', 'Marcella  ', 'Kimberlee  ', 'jgidibvx83@8vfej83.com', '9885 Red Vale', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('33', 'Karyn  ', 'Georgeanna  ', 'vw_f4z@b1embrwcoa.com', '3067 Hazy Zephyr Landing', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('34', 'Kacie  ', 'Lionel  ', 'ix8m@0-h5ol6z7.com', '7357 Rocky Gate Valley', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('35', 'Annabelle  ', 'Johnetta  ', '7vatx3y-@2eu5su8.com', '3673 Sunny Turnabout', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('36', 'Freddie  ', 'Latasha  ', 't6er5llhxf9svfm@df5z7qxxugq.com', '7339 Umber Court', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('37', 'Jere  ', 'Simon  ', 'nau@65xlw9v4t1y.com', '1288 Cozy Farms', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('38', 'Gaston  ', 'Diana  ', '6mn@afb7wys.com', '9002 Merry Beach', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('39', 'Luetta  ', 'Lilla  ', '_ixmi@ega2rxycpg3.com', '5507 Burning Mews', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('40', 'Earlie  ', 'Samatha  ', 'b0to@7yp2jdj.com', '4873 Broad Extension', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('41', 'Colette  ', 'Chara  ', 'iyvv7138@phsdj8kb-rc8.com', '9353 Old Villas', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('42', 'Shamika  ', 'Leonida  ', '6z9v0_6m0b-sw5g@lxvsez3a0.com', '5796 Rustic Ledge', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('43', 'Gerard  ', 'An  ', 'r8-rm3dhk.gdl@ceiuza.com', '4722 Quiet Beacon Private', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('44', 'Vivan  ', 'Debbie  ', 'ylu4.l5-d5p_@15kq8r.com', '1079 Honey Cloud Pathway', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('45', 'Man  ', 'Katelin  ', 'y5i20rkxr_xd@je6iowgsovqe.com', '8759 Iron Pony Orchard', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('46', 'Yuonne  ', 'Yan  ', 'wmhki6cq@s-73vl2gp-l.com', '5859 Dusty Place', '3');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('47', 'Briana  ', 'Kandis  ', '28qhk.@xoon01u.com', '3706 Indian Promenade', '2');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('48', 'Micha  ', 'France  ', 'nmo8lj@x7unc0nniwdd.com', '3918 Green Dell', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('49', 'Victor  ', 'Charley  ', 'na-@2olze69b.com', '9040 Velvet Fox Corners', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('50', 'Cherly  ', 'Alycia  ', 'qcvz2@phcrgq5.com', '2776 Thunder Edge', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('51', 'Ardell  ', 'Rina  ', '0tci7cfw@rqkvki.com', '6430 Stony Carrefour', '1');
INSERT INTO `SurveyDB`.`persons` (`PersonID`, `FirstName`, `LastName`, `Email`, `Location`, `CohortID`) VALUES ('52', 'Kasie  ', 'Debrah  ', 'sbva2kq0m9d@31s4x-665.com', '7057 Noble Wynd', '2');


INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('233', '2', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('234', '3', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('235', '4', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('236', '5', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('237', '6', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('238', '7', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('239', '8', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('240', '9', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('241', '10', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('242', '11', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('243', '12', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('244', '13', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('245', '14', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('246', '15', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('247', '16', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('248', '17', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('249', '18', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('250', '19', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('251', '20', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('252', '21', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('253', '22', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('254', '23', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('255', '24', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('256', '25', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('257', '26', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('258', '27', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('259', '28', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('260', '29', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('261', '30', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('262', '31', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('263', '32', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('264', '33', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('265', '34', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('266', '35', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('267', '36', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('268', '37', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('269', '38', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('270', '39', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('271', '40', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('272', '41', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('273', '42', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('274', '43', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('275', '44', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('276', '45', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('277', '46', '1', '2', 'Other', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('278', '47', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('279', '48', '1', '2', 'Totally confused.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('280', '49', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('281', '50', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('282', '51', '1', '2', 'Great! Excited for the rest of bootcamp.', '', NULL);
INSERT INTO `SurveyDB`.`answer` (`AnswerID`, `PersonID`, `QuestionID`, `SurveyID`, `UserResponse`, `WatsonResponse`, `SubmitDate`) VALUES ('283', '52', '1', '2', 'A little confused, but confident I will get it soon!', '', NULL);
